arch:
    max_epochs: 31
checkpoint:
    save_top_k: 5
    monitor : 'abs_rel_gt'
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'AdamW'
        depth:
            lr: 0.0002
            betas: (0.9, 0.999)
            weight_decay: 0.01
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNetAttention'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (256, 256)
    train:
        batch_size: 8
        dataset: ['custom']
        path: ['/home/sj/colon']
        split: ['train_files.txt']
    validation:
        dataset: ['custom']
        path: ['/home/sj/colon']
        split: ['val_files.txt']  
    test:
        dataset: ['custom']
        path: ['/home/sj/colon']
        split: ['test_files.txt']
