arch:
    max_epochs: 31
checkpoint:
    save_top_k: 5
    monitor : 'abs_rel_gt'
model:
    name: 'SelfSupModel_fbnet'
    optimizer:
        name: 'AdamW'
        depth:
            lr: 0.00006
            betas: (0.9, 0.999)
            weight_decay: 0.01
        depth_feedback:
            lr: 0.00006
            betas: (0.9, 0.999)
            weight_decay: 0.01
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNetCMT'
        version: '18pt'
    depth_net_feedback:
        name: 'DepthResNetCMT'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 4
        dataset: ['KITTI']
        path: ['/home/sj/kitti']
        split: ['eigen_zhou_files_tiny.txt']
        depth_type: ['velodyne']
    validation:
        dataset: ['KITTI']
        path: ['/home/sj/kitti']
        split: ['eigen_val_files_tiny.txt',
                'eigen_test_files_tiny.txt']  
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['/home/sj/kitti']
        split: ['eigen_test_files_tiny.txt']
        depth_type: ['velodyne']
